---
title: "Metode Pencarian Akar"
author: "MUHAMMAD IHSAN SYAFIUL UMAM"
date: "7/2/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1----a
```{r}
library(cmna)
f <- function(x){
  sqrt(x)- cos(x)
}
curve(f, xlim = c(0,1))
abline(h = 0)
abline(v = 0)
```
```{r}
bisection(f,0,1, tol = 0.006, m = 200)
```
1----b
```{r}
f1 <- function(x){
  3*(x+1)*(x-1/2)*(x-1)
}
f1
```
```{r}
# interval [-2,1.5]
bisection(f1,-2,1.5, tol = 0.007, m= 400)
```
```{r}
# interval [-1.25,2.5]
bisection(f1,-1.25,2.5, tol = 0.03, m = 200)
```
1-----c
```{r}
f2 <- function(x){
  x^3 - 2*x^2 +14*x-6
}
f2
```
```{r}
# interval [0.1]
bisection(f2,0,0.1, tol = 0.003, m = 150)
```
```{r}
# interval [1,3.2]
bisection(f2,1,3.2, tol = 0.005, m = 300)
```
```{r}
# interval [3.2,4]
bisection(f2,3.2,4, tol = 10^-2, m = 300)
```
2----a
```{r}
f3<- function(x){
  x^2 -6
}
f3
```

```{r}
library(Deriv)
f3_ <- Deriv(f3)
f3_
```
```{r}
newton(f3,f3_,1, tol = 0.04, m= 200)
```
2-----b
```{r}
f4<- function(x){
  x^3 - 2*x^2+14*x-6
}
f4

```
```{r}
f4_ <- Deriv(f4)
f4_
```

```{r}
newton(f4,f4_,1.5,tol = 0.05,m = 200)
```

